@startuml
클라이언트 -> 서버 : 특정 행위에 대한 요청
서버 -> 서버: 패킷에 송신자 채널 + ID 설정
서버 -> 이벤트_버스 : 수신한 패킷을 버스에 전송한다.
이벤트_버스 -> 이벤트_버스 : 특정 로직을 실행한다.
클라이언트 <- 이벤트_버스 : 클라이언트에 응답 (채널을 이용)
클라이언트 <- 클라이언트 : 받은 응답을 이벤트 버스에 전송한다.
클라이언트 <- 클라이언트 : 이벤트 버스에서 특정 로직을 실행
@enduml