@startuml
object Main

object ServerPresenter
object ServerModel
object ServerView

object DataPresenter
object UserModel
object AccountModel
object RoomModel
object DataModel
object ServerListener

Main --> ServerPresenter
Main --> DataPresenter

ServerPresenter <--> ServerView
ServerPresenter <--> ServerModel
ServerModel --> ServerListener : 등록

DataPresenter <--> DataModel
DataPresenter <--> AccountModel
DataPresenter <--> UserModel
DataPresenter <--> RoomModel
DataPresenter <-- ServerListener

@enduml
