@startuml

object Main
object ServerListener

object ServerPresenter
object ServerModel
object ServerView
object ServerHandler

object DataPresenter
object RoomModel
object AccountModel
object UserModel
object DataModel

object ChannelManager

RoomModel : Room 테이블을 관리하는 기능
AccountModel : Account 테이블을 관리하는 기능
UserModel : Users 테이블을 관리하는 기능

Main : 최초 시작
ServerPresenter : 인터페이스 (Interface)
ServerView : 인터페이스 (Interface)
ServerModel : 인터페이스 (Interface)
DataPresenter : 인터페이스 (Interface)
DataModel : 인터페이스 (Interface) + 실질적인 DB
ServerListener : DataPresenter의 View 역할을 담당한다.
ChannelManager : 사용자에 대한 연결을 담고 있음


Server --|> ServerModel

Main --> ServerView : 입력 이벤트 발생
Main --> DataPresenter : init()

ServerView <--> ServerPresenter : start()\nstop()\nlog()
ServerModel <--> ServerPresenter : start()\nstop()
ServerModel --> ServerHandler : register()

DataPresenter <--> DataModel : getConnection()\ninit()
DataPresenter <--> RoomModel
DataPresenter <--> AccountModel
DataPresenter <--> UserModel
DataPresenter --> ServerPresenter : log()

ServerHandler --> ServerListener : register()\npost()
DataPresenter <-- ServerListener : Query Method
ChannelManager <-- ServerListener : 연결을 관리 및 사용
@enduml
