@startuml
object Main
object ServerController
ServerController : Controller

object ServerUI
object Server
Server : Thread

object ServerHandler
object ServerListener
object LoginListener
object LogoutListener
object RoomCreateListener
object RoomRemoveListener
object RoomJoinListener
object EventBus
object ServerDB
object DataController
object ConnectionPool

ConnectionPool : 각 클라이언트와의 연결을 저장한다.
ServerListener : 기본적인 Listener 뼈대를 구성한다.
LoginListener : 로그인 및 가입에 관련된 패킷을 처리한다.
RoomCreateListener : 룸을 생성하는 이벤트를 처리한다.
RoomRemoveListener : 룸을 제거하는 이벤트를 처리한다.
RoomJoinListener : 룸에 참여하는 이벤트를 처리한다.
ServerDB : SQLite DBMS와 서버를 연결해주는 클래스
DataController : DB에 관련된 일을 처리하는 컨트롤러
LogoutListener : 로그아웃에 관한 일을 처리한다.

Main --> ServerController : 실행
ServerController <--> ServerUI : View
ServerController <--> Server : Model
Server --> ServerHandler : 로직 처리
Server --> EventBus : register()
ServerHandler --> EventBus : post()
EventBus --> ServerListener : handle() by post()
LoginListener --> DataController : 로그인, 가입, 회원 유뮤 확인
LoginListener --> ConnectionPool : 로그인하면 연결을 저장한다.
LogoutListener --> ConnectionPool : 로그아웃하면 연결을 삭제한다.
RoomCreateListener --> DataController : 룸 존재 여부 확인, 룸 생성
RoomJoinListener --> DataController : 룸 존재 여부 확인, 룸 참가, 룸 나가기
RoomRemoveListener --> DataController : 룸 존재 여부 확인, 룸 제거
LogoutListener --> DataController : 로그아웃하면 연결 제거, 상태 변환
DataController --> ServerDB : 연결된 커넥션을 사용한다.
ServerListener <|-- LoginListener
ServerListener <|-- LogoutListener
ServerListener <|-- RoomCreateListener
ServerListener <|-- RoomJoinListener
ServerListener <|-- RoomRemoveListener
@enduml
