@startuml
object NettyListener
NettyListener : 각종 로직을 처리함.

object NettyResponseListener
NettyResponseListener : ChatResponseListener
NettyResponseListener : ConnectResponseListener
NettyResponseListener : ETC ...

object ChatListener
object ConnectListener
object DisconnectListener
object LoginListener
object LogoutListener
object PictureListener
object GuessingListener
object Client

Client --> ServerHandler : 요청 (Datagram)
NettyResponseListener --> Client : 응답 (Datagram)

NettyListener <|-- LoginListener
NettyListener <|-- LogoutListener
NettyListener <|-- ChatListener
NettyListener <|-- ConnectListener
NettyListener <|-- DisconnectListener
NettyListener <|-- PictureListener
NettyListener <|-- GuessingListener
NettyListener --> ClientHandler

ClientHandler --> ClientEventBus : post()
ClientEventBus --> NettyResponseListener : handle()

ServerHandler --> ServerEventBus : post()
ServerEventBus --> NettyListener : handle()

'Object01 <|-- Object02 (상속)
'Object03 *-- Object04
'Object05 o-- "4" Object06 (집합)
'Object07 .. Object08 : some labels (연관)
@enduml
